#!/bin/bash
#
# dvolbar - OSD Volume utility 
#

#Customize this stuff
IF="Master"            # audio channel: Master|PCM
SECS="1"            # sleep $SECS
BG="#242c33"        # background colour of window
FG="#eeeeee"        # foreground colour of text/icon
BAR_FG="#ecedee"    # foreground colour of volume bar
BAR_BG="#777777"    # background colour of volume bar
XPOS="1144"          # horizontal positioning
YPOS="26"          # vertical positioning
HEIGHT="30"         # window height
WIDTH="215"         # window width
BAR_WIDTH="190"     # width of volume bar
FONT="-*-terminus-medium-r-*-*-14-*-*-*-*-*-*-*"

#Probably do not customize
PIPE="/tmp/dvolpipe"

err() {
  echo "$1"
  exit 1
}

usage() {
  echo "usage: dvol [option] [argument]"
  echo
  echo "Options:"
  echo "     -i, --increase - increase volume by \`argument'"
  echo "     -d, --decrease - decrease volume by \`argument'"
  echo "     -t, --toggle   - toggle mute on and off"
  echo "     -h, --help     - display this"
  exit
}

mute_toggle() {
    VOL_FILE="/tmp/cur_vol"
    CUR_VOL=$(amixer get "$IF" | gawk '/Right.+/ {gsub("\\[","", $5);gsub("%\\]", "", $5);printf("%s",$5)}')
    if [[ $CUR_VOL -gt 0 ]]; then
        echo $CUR_VOL > $VOL_FILE
        amixer -q set "$IF" 0%
    else
        VOL=$(cat $VOL_FILE)
        amixer -q set "$IF" ${VOL}%
        rm -f $VOL_FILE
    fi
}

#Argument Parsing
case "$1" in
  '-i'|'--increase')
    [ -z "$2" ] && err "No argument specified for increase."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    AMIXARG="${2}%+"
    ;;
  '-d'|'--decrease')
    [ -z "$2" ] && err "No argument specified for decrease."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    AMIXARG="${2}%-"
    ;;
  '-t'|'--toggle')
      mute_toggle
      MUTE=1
    ;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see dvol --help"
    ;;
esac

#Actual volume changing (readability low)
if [[ -z $MUTE ]]; then
    AMIXOUT="$(amixer set "$IF" "$AMIXARG" | tail -n 1)"
    VOL="$(cut -d '[' -f 2 <<<"$AMIXOUT" | sed 's/%.*//g')"
fi

#Using named pipe to determine whether previous call still exists
#Also prevents multiple volume bar instances
if [ ! -e "$PIPE" ]; then
  mkfifo "$PIPE"
  (dzen2 -tw "$WIDTH" -h "$HEIGHT" -x "$XPOS" -y "$YPOS" -fn "$FONT" -bg "$BG" -fg "$FG" < "$PIPE" 
   rm -f "$PIPE") &
fi

#Feed the pipe!
(echo "$VOL" | gdbar -fg "$BAR_FG" -bg "$BAR_BG" -w "$BAR_WIDTH" ; sleep "$SECS") > "$PIPE"
