#!/bin/bash

#echo "{\"version\":1}"
echo "{ \"version\": 1, \"stop_signal\": 10, \"cont_signal\": 12, \"click_events\": true }"
echo "[[]"
conky -d -c /home/luca/.config/i3/conkyrc

IFS="}"
while read;do
  IFS=" "
  STR=`echo $REPLY | sed -e s/[{}]//g -e "s/ \"/\"/g" | awk '{n=split($0,a,","); for (i=1; i<=n; i++) {m=split(a[i],b,":"); if (b[1] == "\"name\"") {NAME=b[2]} if (b[1] =="\"x\"") {X=b[2]} if (b[1] =="\"y\"") {Y=b[2]} } print NAME " " X " " Y}'`
  read NAME X Y <<< $STR
  X=$(($X-50))
  case "${NAME}" in
    \"updates\")
      notify-send -a "Available updates" -u normal "$(yaourt -Qu)" &
      #yad --button gtk-apply:0 --text-info --geometry=200x200+$X+20 --class "YADWIN" --margins=10 --filename=<(pacman -Sup --print-format="%n %v" | grep -v "^::")
      #if [[ $? -eq 0 ]];then
        #urxvt -H --command "/home/luca/.config/i3/scripts/conkexec.sh sudo pacmatic -Syu" -T "Menu Update"
      #fi
      ;;
    \"mpd_i\")
      mpc --quiet toggle &
      ;;
    \"mpd_r\")
      mpc --quiet random &
      ;;
    \"mpd_t\")
      mpc --quiet prev &
      ;;
     \"mpd_a\")
      mpc --quiet next &
      ;;
     \"mpd_-\")
      mpc --quiet stop &
      ;;
     \"mpd_b\")
      urxvt -title music -e ncmpcpp &
      ;;
    \"date\")
      notify-send -a "Calendar" -u normal "$(cal)" &
      ;;
     \"date_i\")
      yad --no-buttons --geometry=+1054+24 --class "YADWIN" --calendar &
      sleep 10 && killall yad &
      ;;
    \"time\")
      keepassx &
      ;;
    \"temp\")
      notify-send -a "Temperatures" -u normal "$(temp_nc)" &
      ;;
    \"bat\")
      notify-send -a "Battery" -u normal "$(sh ~/.config/i3/scripts/battery)" &
      ;;
    \"net_up\")
      notify-send -a "External IP" -u normal "$(sh ~/.config/i3/scripts/ip-external)" &
      ;;
    \"net_down\")
      notify-send -a "Internal IP" -u normal "$(sh ~/.config/i3/scripts/ip-internal)" &
      ;;
    \"net_up_i\")
      opera &
      ;;
     \"net_down_i\")
      chromium &
      ;;
    \"kernel\")
      notify-send -a "Memo" -u normal "$(cat ~/.reminders)" &
      ;;
    \"home\")
      notify-send -a "Disks mounted" -u normal "$(dfc -d | grep /dev/sda && dfc -d | grep /dev/sdb)" &
      ;;
    \"fsicon\")
      pcmanfm &
      ;;
    \"mem\")
      notify-send -a "RAM" -u normal "$(free -m | grep total && free -m | grep Mem)" &
      ;;
    \"bright\")
      ~/.config/i3/scripts/lightdown &
      ;;
     \"bright_i\")
      ~/.config/i3/scripts/lightup &
      ;;
    #\"bright\")
      #LEVEL=`/home/luca/.config/i3/scripts/blevel.sh`
      #OUT=`yad --scale --value $LEVEL --button gtk-ok:0 --geometry=100x300+$X+20 --class "YADWIN" --vertical --text-align center`
      #if [[ $? -eq 0 ]];then
        #Q=`/home/luca/.config/i3/scripts/conkexec.sh sudo light $OUT`
      #fi
      #;;
    \"volume\")
      pavucontrol &
      ;;
    #\"volume\")
      #VOL=`/home/luca/.config/i3/scripts/pacvol.sh display | sed "s/[^1-9]//" | sed "s/%//"`
      #OUT=`yad --text="Volume" --scale --value $VOL --button gtk-ok:0 --geometry=x200+$X+20 --class "YADWIN" --vertical --text-align center`
      #if [[ $? -eq 0 ]];then
        #TARGET="$((655*$OUT))"
        #/home/luca/.config/i3/scripts/conkexec.sh pacmd set-sink-volume 0 $TARGET
      #fi
      #;;
    *)
      ;;
  esac
  IFS="}"
done
