#!/bin/sh
lock() {
    i3lock -d -p default -i /media/Dati/Dropbox/Wallpapers/suburb.png
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        #xfce4-session-logout
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {kill|lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac
