#!/bin/sh

case "$1" in
    temp)
        notify-send -a "Temperatures" -u normal "$(temp_nc)"
        ;;
    disk)
        #i3-msg exit
        notify-send -a "Disks mounted" -u normal "$(dfc -d | grep /dev/sda && dfc -d | grep /dev/sdb)"
        ;;
    ip)
        notify-send -a "External IP" -u normal "$(sh ~/.config/i3/scripts/ip-external)"
        ;;
    cal)
        notify-send -a "Calendar" -u normal "$(cal)"
        ;;
    bat)
        notify-send -a "Battery" -u normal "$(sh ~/.config/i3/scripts/battery)"
        ;;
    updates)
        notify-send -a "Available updates" -u normal "$(yaourt -Qu)"
        ;;
    *)
        echo "Usage: $0 {temp|disk|ip|cal|bat|updates}"
        exit 2
esac
