#!/bin/sh

brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

if (($brightness > 0)); then
  let brightness=$brightness-235,5
    echo "echo $brightness > /sys/class/backlight/intel_backlight/brightness" | sudo zsh
fi
