#!/bin/sh

max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

if (($brightness < $max_brightness)); then
  let brightness=$brightness+235,5
  echo "echo $brightness > /sys/class/backlight/intel_backlight/brightness" | sudo zsh
fi
