#!/bin/sh

brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

if (($brightness > 0)); then
  let brightness=$brightness-3061,5
    echo "echo $brightness > /sys/class/backlight/intel_backlight/brightness" | sudo zsh
fi
