#!/bin/bash
DPMS=$(xset q | grep "DPMS is Disabled")
echo $DPMS
if [ "$DPMS" == "" ]; then
	xset -dpms
	notify-send -t 500 -a "Screensaver" "Disabled"
else
	xset +dpms
    xset dpms 600
    killall xss-lock && xss-lock -- i3lock -d -p default -i /home/luca/Immagini/Wallpapers/wall.png &
	notify-send -t 500 -a "Screensaver" "Enabled"
fi;
